### ISSUE TITLE
runbooks website uses inappropriate SSL certificate

### ISSUE THREAD

**Issue by VasylTretiakov** [starkandwayne/runbooks#4]
the website URL is _https://runbooks.starkandwayne.com_ while the SSL certificate is issued to  _*.run.pivotal.io_
![Screenshot_20200212-144241_Chrome](https://user-images.githubusercontent.com/3999712/74336138-630e1a80-4da6-11ea-944a-1366a78117a8.jpg)

**Comment by xiujiao** [comment]
it is fixed now
